service: identity-reconciliation

framework: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, env:STAGE, 'dev'}
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

  httpApi:
    cors: true


functions:
  identify:
    handler: src/lambdas/identify/handler.handler
    events: 
      - httpApi:
          path: /identify
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline


package:
  individually: true
  patterns:
    - '!**/*.test.ts'
    - '!**/*.spec.ts'
    - 'node_modules/.prisma/**'
    - 'node_modules/@prisma/client/**'
    - '!prisma/dev.db'
    - '!prisma/.env'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
    concurrency: 10
    external:
      - '@prisma/client'
      - '.prisma/client'
